export const teamName1 = [
    "Arsenal",
    "Aston Villa",
    "Brentford",
    "Brighton & Hove Albion",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Leeds United",
    "Leicester City",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Norwich City",
    "Southampton",
    "Tottenham Hotspur",
    "Watford",
    "West Ham United",
    "Wolverhampton Wanderers"
  ];
export const teamName = [
  "arsenal",
"aston villa",
"bournemouth",
"brentford",
"brighton",
"chelsea",
"crystal palace",
"everton",
"fulham",
"leeds united",
"leicester city",
"liverpool",
"manchester city",
"manchester utd",
"newcastle utd",
"nott'ham forest",
"southampton",
"tottenham",
"west ham",
"wolves",

]  